# Generated by Django 5.2.6 on 2025-10-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
