# Generated by Django 5.2.6 on 2025-10-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_alter_bill_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.IntegerField(unique=True),
        ),
    ]
